### ISSUE TITLE
Startup and Shutdown icon is too dark in Midna Dark

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/midna#13]
When i type Autostart in the search box, the Startup and Shutdown icon looks grey out, while it actually contains the KCM, especially of course with low brightness on the screen: 

![screenshot_20170617_105618](https://user-images.githubusercontent.com/6344099/27251716-bee90c40-534c-11e7-9f0f-17693f75e699.png)

**Comment by demmm** [comment]
Midna dark is not maintained by KaOS (and never has been, always been a user maintained addition).  Any user who wishes it updated or fixed can help by creating pull requests.  Issues won't be addressed for it.
