### ISSUE TITLE
Use of icons

### ISSUE THREAD

**Issue by fabianalexisinostroza** [KaOSx/midna#14]
I recently see you are merge my new icons on midna theme. My new icon theme is made from scratch and use the LIMA Licence. This is not a refresh of old Antü theme (called now Antü Classic on my Github).

Please don't use my new icon theme, use the classic antü theme for midna improvements. 

Solicito que se realicen las regresiones correspondientes, no autorizo a KaOS a usar mi nuevo tema de iconos, como tampoco a la re-licencia de los mismos. Ya que se ha incumplido la licencia LIMA, que exige el contacto previo con el creador del contenido.

De no haber respuesta, me veré obligado a denunciar a Github.

**Comment by demmm** [comment]
Updates will be removed.

**Comment by demmm** [comment]
Removed.
