### ISSUE TITLE
Some Midna icon theme icons are out of styling

### ISSUE THREAD

**Issue by IevgenSobko** [KaOSx/midna#15]
Some Midna icon theme icons are out of styling.
At the same time dark icons theme looks ok.
![screenshot_20180318_132428](https://user-images.githubusercontent.com/14232100/37565315-cc8b90a8-2aaf-11e8-854e-d37788fa7096.png)

**Comment by demmm** [comment]
Thanks for checking.  After redoing some 2500 icons, missing some is inevitable.  Pull request always welcome, and if you find more, please note.
