### ISSUE TITLE
Missing discover icon in Midna Dark

### ISSUE THREAD

**Issue by rgedda** [KaOSx/midna#16]
Midna Dark does not have a notification icon for Discover:

* https://www.gedda.info/?p=1226#comment-4890

**Comment by rgedda** [comment]
Hi there,

Any update on this?

**Comment by demmm** [comment]
With the lack of response, you can note, those who submitted midna dark are no longer interested in it :(.

**Comment by demmm** [comment]
Might be it is addressed in https://github.com/KaOSx/midna/pull/20

**Comment by demmm** [comment]
No further response from submitter.
