### ISSUE TITLE
Question about the copyright

### ISSUE THREAD

**Issue by freefreeno** [KaOSx/midna#17]
I see the repo has the normal GPLv3 license but with the copyright say I wanted to use only the folders from the Midna icons and recolor them and change a few things can I use them for my theme?? I just don't want to do something stupid. Normally ya know with the GPLv3 the person might not like it but as long as credit is given then it is fine. Thanks in advance.

**Comment by demmm** [comment]
License allows you to fork and alter as you please, as long as you keep it opensource too (simply put).

**Comment by freefreeno** [comment]
@demmm Oh of course it will be opensource but really I guess I should have asked the question like this. Do I have to include the copyright file??? Sorry I wasn't clear and thanks for the response back.

**Comment by demmm** [comment]
Yes, license needs to stay with the files.

**Comment by freefreeno** [comment]
@demmm Not license. The copyright file. The copyright file is not a license but I am making sure we are speaking about the same thing. I have never had to add a copyright file to any opensource products. There is a copyright in the repo and that is not a license but it has some wording in it that makes me think I have  include but I have never had to include a copyright file in opensource products before. I want to just include the GPL license so will this be ok ????? I can not use the folders if I have to include a copyright file but I can use the GPLv3. So this would make it NOT opensource.

**Comment by demmm** [comment]
>The copyright file

There is not one file, there are several license files (which include copyright text).  The different licenses are for different parts of Midna.  Wallpapers for example are from numerous artists, all using different licenses.

**Comment by freefreeno** [comment]
@demmm I  just need to know if I can use the folders with only the GPLV3????

**Comment by demmm** [comment]
Yes, icons are GPLv3

**Comment by freefreeno** [comment]
> Yes, icons are GPLv3

Thank you so I will include the GPLv3 license in the folders but not the copyright.
