### ISSUE TITLE
How to install this theme on Kubuntu

### ISSUE THREAD

**Issue by gaganyadav80** [KaOSx/midna#22]
Hello, I really liked this midna theme and wanted to try it out. But due to limited available packages in KaOS I decided to go with ubuntu and found this repository. But I don't know how to install this theme. I tried moving the /icons/mida folder to ~/.icons but it was not recognised in settings->icons and then I moved it to /usr/share/icons/ and then it was in the settings->icon but it is broken as I can not see the folder icons.

How do I install he complete midna theme in Kubuntu? Please Help.

**Comment by demmm** [comment]
Midna uses cmake to build and install, see the file:
https://github.com/KaOSx/midna/blob/master/CMakeLists.txt
or the PKGBUILD:
https://github.com/KaOSx/apps/blob/master/midna-themes/PKGBUILD
Just a normal cmake/make/make install.
But bug reports are not for requiring help, or trying to figure how another distro builds packages.
