### ISSUE TITLE
KDE store

### ISSUE THREAD

**Issue by noraj** [KaOSx/midna#25]
I may have missed an earlier discussion, what about publishing a midna global theme to https://store.kde.org/browse/ so it could be browsed and installed via Plasma UI?

![image](https://github.com/KaOSx/midna/assets/16578570/1564a955-13fc-47d2-b0d8-0911f2943a3f)

**Comment by demmm** [comment]
Midna is purley & solely developed by and for KaOS, no plan to publish or support it anywhere else.
